In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
#!pip install tensorflow

In [3]:
import tensorflow as tf

In [4]:
df=pd.read_csv("diabetes.csv")

In [5]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [7]:
x=df.iloc[:,0:-1].values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
y=df["Outcome"].values
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [9]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=0.2)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [11]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import classification_report


In [12]:
ann=Sequential()

In [13]:
ann.add(Dense(units=10,activation="relu"))
ann.add(Dense(units=10,activation="relu"))
ann.add(Dense(units=1,activation="sigmoid"))


In [14]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [15]:
ann.fit(xtrain,ytrain,batch_size=25,epochs=100)
yp=ann.predict(xtest)

Epoch 1/100
25/25 [==============================] - 1s 3ms/step - loss: 0.6840 - accuracy: 0.5635
Epoch 2/100
25/25 [==============================] - 0s 2ms/step - loss: 0.6489 - accuracy: 0.6661
Epoch 3/100
25/25 [==============================] - 0s 2ms/step - loss: 0.6210 - accuracy: 0.6922
Epoch 4/100
25/25 [==============================] - 0s 2ms/step - loss: 0.5968 - accuracy: 0.6938
Epoch 5/100
25/25 [==============================] - 0s 2ms/step - loss: 0.5768 - accuracy: 0.7182
Epoch 6/100
25/25 [==============================] - 0s 2ms/step - loss: 0.5607 - accuracy: 0.7231
Epoch 7/100
25/25 [==============================] - 0s 2ms/step - loss: 0.5470 - accuracy: 0.7329
Epoch 8/100
25/25 [==============================] - 0s 2ms/step - loss: 0.5363 - accuracy: 0.7345
Epoch 9/100
25/25 [==============================] - 0s 2ms/step - loss: 0.5269 - accuracy: 0.7410
Epoch 10/100
25/25 [==============================] - 0s 2ms/step - loss: 0.5192 - accuracy: 0.7410
Epoch 11/

25/25 [==============================] - 0s 2ms/step - loss: 0.4291 - accuracy: 0.7948
Epoch 84/100
25/25 [==============================] - 0s 2ms/step - loss: 0.4291 - accuracy: 0.7964
Epoch 85/100
25/25 [==============================] - 0s 2ms/step - loss: 0.4290 - accuracy: 0.7948
Epoch 86/100
25/25 [==============================] - 0s 2ms/step - loss: 0.4275 - accuracy: 0.7964
Epoch 87/100
25/25 [==============================] - 0s 2ms/step - loss: 0.4286 - accuracy: 0.7980
Epoch 88/100
25/25 [==============================] - 0s 2ms/step - loss: 0.4271 - accuracy: 0.7997
Epoch 89/100
25/25 [==============================] - 0s 2ms/step - loss: 0.4266 - accuracy: 0.7997
Epoch 90/100
25/25 [==============================] - 0s 2ms/step - loss: 0.4260 - accuracy: 0.7948
Epoch 91/100
25/25 [==============================] - 0s 2ms/step - loss: 0.4257 - accuracy: 0.8013
Epoch 92/100
25/25 [==============================] - 0s 3ms/step - loss: 0.4251 - accuracy: 0.7997
Epoch 93/100


In [16]:
#yp=yp>0.5

In [17]:
yp=np.where(yp<0.5,0,1)
yp

array([[1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [18]:
print(classification_report(ytest,yp))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86       107
           1       0.68      0.64      0.66        47

    accuracy                           0.80       154
   macro avg       0.76      0.75      0.76       154
weighted avg       0.80      0.80      0.80       154



In [19]:
df["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64